apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: orion-web
      namespace: orion-stg
      labels: {app.kubernetes.io/name: orion-web, app.kubernetes.io/instance: orion-stg, app.kubernetes.io/part-of: orion, app.kubernetes.io/managed-by: platform}
    spec:
      selector: {matchLabels: {app.kubernetes.io/name: orion-web}}
      template:
        metadata:
          labels: {app.kubernetes.io/name: orion-web, app.kubernetes.io/instance: orion-stg, app.kubernetes.io/part-of: orion, app.kubernetes.io/managed-by: platform}
        spec:
          containers:
            - name: web
              image: nginx:latest
              env:
                - {name: DB_PASSWORD, value: hunter2}
